#!/usr/bin/python

import os,sys

sys.path.append(os.path.expanduser('~'))
sys.path.append(os.path.expanduser('~') + '/ROOT/')

from werkzeug.wsgi import DispatcherMiddleware
from wt import dashboard

application = DispatcherMiddleware(dashboard.create_app(config_name="production")
)